# Generated by Django 3.1.1 on 2020-10-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='status',
        ),
    ]
