# Generated by Django 3.1.1 on 2020-09-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0002_auto_20200902_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='dated_order',
            new_name='dated',
        ),
    ]
