# Generated by Django 3.1.1 on 2020-09-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0003_auto_20200902_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
