# Generated by Django 3.1.1 on 2020-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0004_auto_20200907_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
