# Generated by Django 3.1.1 on 2020-09-02 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0004_stockin_buying_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('country', models.CharField(choices=[('japan', 'japan'), ('philipines', 'philipines'), ('pakistan', 'pakistan')], default='japan', max_length=100)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_stockout', to='japan_inventory.stockin')),
            ],
        ),
    ]
