# Generated by Django 3.1.1 on 2020-10-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0004_carpartsstockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbuypart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
