# Generated by Django 3.1.1 on 2020-09-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0006_stockin_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
