# Generated by Django 3.1.1 on 2020-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0006_remove_invoice_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Available', 'Sold')], default='Available', max_length=100),
        ),
    ]
