# Generated by Django 3.1.1 on 2020-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_inventory', '0007_stockin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='status_car',
            field=models.BooleanField(default=True),
        ),
    ]
