# Generated by Django 3.1.1 on 2020-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pak_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='status_car',
            field=models.BooleanField(default=True),
        ),
    ]
