# Generated by Django 3.1.1 on 2020-09-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pak_inventory', '0002_stockin_status_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_type',
        ),
    ]
