# Generated by Django 3.1.1 on 2020-09-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pak_inventory', '0003_auto_20200923_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='chasis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
