# Generated by Django 3.1.1 on 2020-11-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philip_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpartsstockout',
            name='stock_out_quantity',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
