# Generated by Django 3.1.1 on 2020-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philip_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='stockin',
            name='status_car',
            field=models.BooleanField(default=True),
        ),
    ]
